@echo off
echo Stopping all Node processes...
taskkill /F /IM node.exe 2>nul

echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul

echo Cleaning .next directory...
if exist .next rmdir /s /q .next

echo Starting dev server...
npm run dev
